### ISSUE TITLE
Fn / FnMut

### ISSUE THREAD

**Issue by gl-yziquel** [rust-bakery/nom#1765]
Hi.

Coming from a functional programming background, I tend to like immutability rather than mutability. I was surprised to see that nom uses FnMut instead of Fn, and discovered the following discussion as well as a few issues.

https://github.com/rust-bakery/nom/pull/1002

So, I understand that nom moved from Fn to FnMut, historically.

I have a use case which would be better off with Fn than FnMut. I essentially use the rpds crate for fully persistent datastructures for my parsing, and as the datastructures I am using do not implement the Copy trait, and as I do not want to clone either (which should nonetheless be ok-ish with rpds), I pass these datastructures through refs. Moreover, I want my parser to have no heap allocation. So, basically, I kick the can down the road, or, rather, the ownership down the stack.

The problem with FnMut then is the following. When I implement the nom Parser trait after battling with flat_map, I get a struct, which has refs to such that rpds datastructures. And as the process method requires a &mut self, I cannot move out of these rpds datastructures, because they are hidden behind a mutable reference.

Which is rather unfortunate.

So...

... would it be conceivable (in the long run) to duplicate the interface into Fn and not only FnMut ? Or is there anything deeper, technical or social, that I am missing ?

**Comment by Xiretza** [comment]
Can you provide a code example that illustrates the problem? I don't understand how restricting something to `Fn` rather than the more general `FnMut` would help.

**Comment by gl-yziquel** [comment]
As of now, I can't extract a snippet from the codebase without spending a huge amount of time in refactoring. Maybe I will manage to do so in the next week. Dunno. I'll try some brief explanation, though. (Pseudo-code likely will be bogus, as I do not yet have the feel for rust syntax. Apologies...)

Bottom line:

Suppose you want to implement a Parser for some use with flat_map. Say you've parsed some argument literals for a lambda calculus dialect, and you've extracted the data of `a`, `b`, `c` from the "let f a b c = (a b) c" string. The data of the a, b, c literals gets parsed to some args. You then construct a subparser this way that owns the Vec of such literals this way.

```rust
struct SubParser<'subparser_lifetime> {
    parent: &'subparser_lifetime ParentParser,
    args: Vec<'subparser_lifetime str>
}
```

I then try to combine that with flat_map like this (in 8.0.0-alpha2):

```rust
flat_map(arguments_extractor, |args: Vec<&str>| SubParser(self, args))
```

Now, the ParentParser contains a reference to some rpds::HashTrieMap<String, Lambda> data structure holding the bindings of literals to lambda terms. (I am not using a parse tree: I trie to use nom to construct the lambda terms as a cyclically implemented datastructure directly in a bumpalo arena, and I wish to avoid, ultimately, all heap allocation; otherwise, using rust compared to other languages does not seem worth the trouble.)

So, If I want to update these bindings, I need to implement a new rpds::HashTrieMap. As I want to put it on the stack, and not the heap, I create, in the process() method of the SubParser such an rpds::HashTrieMap.

However, 1. rpds::HashTrieMap does not implement the Copy trait, and, it seems, rightly so. And 2. to access the original rpds::HashTrieMap to contain my new one, I need to perform a move, and the FnMut here gets in the way of that move where Fn would likely not.

I understand this is a niche case: no heap allocation, fully persistent datastructures and no mutability, direct parsing from string to executable-ish lambda calculus. Nonetheless, it seems it is a case where FnMut gets in the way if one wishes not to use Box or anything else like that.

I'll try to extract some code snippet, but please don't hold your breath: I'm currently in ugly refactoring mode around this code.

**Comment by Xiretza** [comment]
Are you sure what you want is `Fn` and not `FnOnce`?

**Comment by gl-yziquel** [comment]
&dyn FnOnce has problems being stack allocated. It's special. I had a very long chat with ChatGPT about it. So, no, I guess.

**Comment by Xiretza** [comment]
> `&dyn FnOnce`

You can't call an `FnOnce` through a reference, it's called by value. Not sure how you ended up at a trait object anyway, `nom` uses generics almost exclusively.

> I had a very long chat with ChatGPT about it

That explains a lot.

**Comment by gl-yziquel** [comment]
FnOnce captures too much.  I need to be able to reference my datastructure that are higher up in the stack. Can't move them, or my lifetimes get incoherent. I need to keep these references to keep track of my lifetimes.

**Comment by gl-yziquel** [comment]
I'll reopen once I have code samples handy.

**Comment by maartendeprez** [comment]
I was affected by this issue, when I tried to use a parser passed in as an argument multiple times. To be able to re-use the parser, it must be `Clone` or `Copy`. One way to do so, is to pass it in by shared reference. Sharing a parser like this, works for `impl Fn` parsers, but not for `impl FnMut` parsers, since `FnMut` is only implemented for `&mut impl FnMut`, not for `&impl FnMut`.

Nom's primitive parsers return `impl Fn` parsers, that can be used even when `impl FnMut` (or `nom::Parser`, which is implemented for `FnMut`) is expected. The problem appears with nom combinators, that take `impl FnMut` parsers as argument and consequently have to return `impl FnMut` parsers, instead of the more general (in return position) `impl Fn`. Even though the concrete type would implement `Fn`, provided that the argument does, we are barred from using it as such because RPIT does not allow that information to get through.

In summary, accepting `FnMut` in argument position is more general with respect to the parsers passed in, but makes the returned parsers less general. Ideally, we'd want combinators to return `impl Fn` when all parser arguments are `impl Fn` (unless of course the combinator itself requires `FnMut` for some reason). One simple way to do so, would be to provide separate `combinator` and `combinator_mut` versions, although that doesn't look very elegant.

A simple workaround in the example below, is to take a `Factory: Fn() -> impl Parser` as argument and call that whenever the parser is needed.

[Code sample:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=90a1954a16e75ead872c0d5c786ac2e7)
```rust
#[derive(Debug)]
enum Param {
    Value,
    User(String),
}

impl FromStr for Param {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        fn param<
            'a: 'p,
            'p,
            Name: 'p,
            NameParser: Fn(&'a str) -> IResult<&'a str, Name> + 'p,
            ParamBuilder: Fn(Name) -> Param + 'p,
        >(
            name: &'p NameParser,
            f: &'p ParamBuilder,
        ) -> impl nom::Parser<&'a str, Param, nom::error::Error<&'a str>> + 'p {
            alt((
                map(preceded(char('$'), name), f),
                map(delimited(tag("${"), name, char('}')), f),
            ))
        }

        let value_param_parser = tag("value");
        // let user_param_parser =
        //     preceded(tag("params."), take_while1(|c: char| c.is_alphanumeric()));
        let parser = alt((
            // This works fine: &value_param_parser implements nom::Parser<_,_,_>
            param(&value_param_parser, &|_| Param::Value),
            // This is not possible, since &user_param_parser does not implement nom::Parser<_,_,_>
            // param(&user_param_parser, &|name: &str| {
            //     Param::User(name.to_string())
            // }),
        ));

        let r = terminated(parser, eof)(s)
            .finish()
            .map(|(_, r)| r)
            .map_err(|_| "failed to parse");
        r
    }
}
```
